include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: 
    - '**.g.dart'
    - '**.freezed.dart'
    - '**/generated/**'
  
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_use_package_imports
    - prefer_single_quotes
    - avoid_classes_with_only_static_members
    - always_specify_types